### ISSUE TITLE
finding requested reports

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/standard-reports-ui#11]
Assume i'm a new user - I request a report and see its going to take 15 minutes to complete - I then start to request a new report and submit that one, I now have two reports in the queue - how do i go back and get the first one?

**Comment by der** [comment]
You make a note of the URL for the first one and go back to it. That's what browser tabs are for :)

If it's too late for that then if you request the same report again you will end up back at same URL and will see status of the previous request. It won't reissue the request if it seems there's an identical one already in progress.

**Comment by MalcolmShazell** [comment]
ok - we'll need to document that in the user instructions - i'll take that away to Alison
