### ISSUE TITLE
Add underlines to text links

### ISSUE THREAD

**Issue by DanielCouzens** [epimorphics/standard-reports-ui#114]
- [x] [1.4.1: Use of Color](https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1282556960#gid=1282556960&range=A5)
- [x] [1.4.1: Use of Color - part 2](https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1282556960#gid=1282556960&range=A6)

**Comment by DanielCouzens** [comment]
I have created two PRs in two repo's because the link text in this case is requires updates to the following repos. 

Standard reports repo https://github.com/epimorphics/standard-reports-ui/pull/121
Lr common styles repo https://github.com/epimorphics/lr_common_styles/pull/60

**Comment by DanielCouzens** [comment]
When creating a PR I am having build issues

**Comment by DanielCouzens** [comment]
Build issues fixed please see the following PR's

Standard reports repo https://github.com/epimorphics/standard-reports-ui/pull/121
Lr common styles repo https://github.com/epimorphics/lr_common_styles/pull/60

**Comment by DanielCouzens** [comment]
Lr common styles repo https://github.com/epimorphics/lr_common_styles/pull/60 has been merged

**Comment by DanielCouzens** [comment]
Standard reports repo https://github.com/epimorphics/standard-reports-ui/pull/121 has been merged

**Comment by tomguilbert** [comment]
looks good thanks @DanielCouzens
