### ISSUE TITLE
Improve link text

### ISSUE THREAD

**Issue by DanielCouzens** [epimorphics/standard-reports-ui#115]
- [x] [2.4.4: Link Purpose (In Context)](https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1282556960#gid=1282556960&range=A8)

**Comment by DanielCouzens** [comment]
I have created a PR https://github.com/epimorphics/standard-reports-ui/pull/122

**Comment by DanielCouzens** [comment]
When creating a PR I am having build issues

**Comment by DanielCouzens** [comment]
Build issues fixed please see PR https://github.com/epimorphics/standard-reports-ui/pull/122

**Comment by DanielCouzens** [comment]
PR https://github.com/epimorphics/standard-reports-ui/pull/122 has been merged

**Comment by tomguilbert** [comment]
It's a bit hidden, but I think the requirement also calls for more descriptive image alt text - something that actually describes the content of the images to a visually impaired user.

**Comment by DanielCouzens** [comment]
I have updated the alt text. @tomguilbert this is ready to check in the dev instance

**Comment by tomguilbert** [comment]
Thanks @DanielCouzens this looks good
