### ISSUE TITLE
Page titles

### ISSUE THREAD

**Issue by DanielCouzens** [epimorphics/standard-reports-ui#116]
- [x] [2.4.2: Page Titled](https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1282556960#gid=1282556960&range=A7)

**Comment by DanielCouzens** [comment]
There is a PR for common styles to update the title tag please see here https://github.com/epimorphics/lr_common_styles/pull/61

**Comment by DanielCouzens** [comment]
This is in review. PR https://github.com/epimorphics/standard-reports-ui/pull/128

**Comment by DanielCouzens** [comment]
PR https://github.com/epimorphics/standard-reports-ui/pull/128 is merged into dev

**Comment by tomguilbert** [comment]
looks good thanks @DanielCouzens
