### ISSUE TITLE
Consistent Help

### ISSUE THREAD

**Issue by DanielCouzens** [epimorphics/standard-reports-ui#117]
- [x] Style the help button the same way as PPD [3.2.6: Consistent Help](https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1282556960#gid=1282556960&range=A9)

**Comment by DanielCouzens** [comment]
This is in review, PR https://github.com/epimorphics/standard-reports-ui/pull/123

**Comment by DanielCouzens** [comment]
PR https://github.com/epimorphics/standard-reports-ui/pull/123 has been merged

**Comment by tomguilbert** [comment]
looks good thanks @DanielCouzens
