### ISSUE TITLE
Input error identification

### ISSUE THREAD

**Issue by DanielCouzens** [epimorphics/standard-reports-ui#118]
- [x] [3.3.1: Error Identification](https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1282556960#gid=1282556960&range=A10)

**Comment by DanielCouzens** [comment]
This is in review see PR https://github.com/epimorphics/standard-reports-ui/pull/124

**Comment by DanielCouzens** [comment]
PR https://github.com/epimorphics/standard-reports-ui/pull/124 been merged into dev

**Comment by tomguilbert** [comment]
looks good thanks @DanielCouzens
