### ISSUE TITLE
Large report completion failure left queue stuck

### ISSUE THREAD

**Issue by der** [epimorphics/standard-reports-ui#12]
A request for 
```
area=EW&controller=download_report&period=2015&areaType=country&utf8=✓&report=banded&sticky=true&action=show&age=any&aggregate=pcSector
```
failed during the xls generation phase but left the queue stuck requiring manual intervention.

1. Underlying cause is suspected to be tomcat memory limits generating the xls. May need to move to streaming xls generation or significantly raise memory limits.

2. The request should have been marked as failed rather than left as InProgress

**Comment by der** [comment]
Believed fixed.

Failure was due to xlsx generation running in memory combined with low memory setting of tomcat server. Appears to have not hit out of memory (in which case would have seen a retry attempt) but was suffering GC thrashing and grinding to a halt. This was made worse by a fault in the retry-if-failed logic.

Replicated on local workstation, fixed the retry logic, switch to a streaming version of xlsx, which runs locally with same memory limits as the dev server.

New version of report manager built and deployed to dev server.

Please test again.

**Comment by der** [comment]
Note: I've also cleared the caches so that any new requests have to start over, just to make sure any test really exercises the report manager.

**Comment by MalcolmShazell** [comment]
retested and job completed correctly
