### ISSUE TITLE
Links to downloaded reports missing icons

### ISSUE THREAD

**Issue by carl-t** [epimorphics/standard-reports-ui#13]
As discussed on Slack, the download page displays file names consistently but there is no icon indicating a link.  Slightly different behaviour between browsers but the problem is most obvious in Chrome.

**Comment by ijdickinson** [comment]
OK, I think the deployed change has fixed the problem, if you'd like to confirm.

**Comment by carl-t** [comment]
Looks good, tested in Chrome, IE and FireFox.
