### ISSUE TITLE
File name possibly misleading when date range spans two years

### ISSUE THREAD

**Issue by carl-t** [epimorphics/standard-reports-ui#14]
If a date range covers two years such as "2016 and 2015" then the file name only references the first year.

Example:
I generate a report for 2016, download it, the file name will end -2016.xlsx.  I then step back to the date section, add all of 2015 to the date range so my summary now says "dates are 2016 and 2015", and generate the report.  The modified report will have the same -2016 file name, i.e. it does not reflect the 2015 data.

**Comment by der** [comment]
Confused. We don't generate multi-year reports. That was something we checked early on. If you want multiple years or multiple specific quarters then that's multiple reports. So for two years you are supposed to end up with a report for each year.

**Comment by carl-t** [comment]
My mistake, sorry - the first report was cached and came really quickly, whereas the the additional 2015 data took some time and I didn't notice it as a separate report.

**Comment by carl-t** [comment]
I'll close this as invalid.
