### ISSUE TITLE
Update Report Options (FS31) can lead to invalid combinations

### ISSUE THREAD

**Issue by carl-t** [epimorphics/standard-reports-ui#15]
I can change one of my choices at step 7, but the workflow does not force me to update any other dependent choices.  This can lead to an invalid report configuration.

Example - I generate an England/Wales "Country" report, grouped by County.  From the Summary step (7) I change the area type to Postcode Area.  On clicking next I am taken back to the Summary section with all the other options unchanged; I will generate a report with area type pcArea but postcode area will be "EW" (England/Wales), aggregating by County (which is invalid).

![image](https://cloud.githubusercontent.com/assets/16542988/13004121/6957d210-d171-11e5-958d-441bdd5aed0f.png)

**Comment by ijdickinson** [comment]
So I agree that this is a possibility, but I'm not sure it's worth fixing. The fix would be to always remove contingent values when the user goes back to change a value. So in going back to change the area type, we would automatically remove the selections for area and aggregate-by, forcing the user to restate all of those values again. But if the user doesn't change the actual value (i.e. they go to the 'change' page, but select the same value as before) then they would still have to choose the area and aggregate-by.

Conversely, we could argue that if some wants to change the report to a different area type and area, while keeping the other options fixed (and I don't think this would be very common) they have to make two 'change' operations, and in-between time the report is not in a valid configuration. Alors.

I can imagine a possible way to do a complete fix, by changing the workflow to keep before- and after- values during the dialogue, but it would add a lot of complexity and I'm not sure that the end-user value is worth it.

Suggest we discuss this at the next Monday call.

**Comment by carl-t** [comment]
OK, to be discussed.  Issue #16 covers the "different type" scenario, it's all the same thing really.

**Comment by ijdickinson** [comment]
The situation is now better. I have added validation rules, so that the workflow traversal checks for valid existing values when moving between steps. This fixes problems like changing the area-type to "county" when the current area is "England and Wales". One remaining problem is that the aggregation type is not yet validated. So if you design a report to be aggregated by county, then change the area type to postcode sector, you can end up with a set of report options that you wouldn't normally have been able to select. Again, we should evaluate whether fixing this meets cost/benefit considerations.

**Comment by ijdickinson** [comment]
Suggest we close this general issue (subject to confirmation), and open a specific subsidiary issue regarding the aggregation type ... which we can then discuss and decide whether or not to fix.

**Comment by carl-t** [comment]
Will close this issue and open one specific to aggregation
