### ISSUE TITLE
Changing a report type from Average Price to Banded clears all options

### ISSUE THREAD

**Issue by carl-t** [epimorphics/standard-reports-ui#16]
Step 7 summary, if I change my mind about the report type, i.e. I chose Banded but I now want Average Price, I have to re-enter all the same choices.  This is the same as the "back to start" behaviour although all the options seem to be passed in the URL.

**Comment by ijdickinson** [comment]
Fix deployed

**Comment by carl-t** [comment]
Looking good, will close.
