### ISSUE TITLE
Step Number indicator out of sequence after step 7 changes

### ISSUE THREAD

**Issue by carl-t** [epimorphics/standard-reports-ui#17]
If my step 7 Summary changes invalidate the county (e.g. change from a Postcode area to a County area), I am prompted to re-enter the county on the usual 'Select a county' screen but the progress indicator shows it as 'Step 7 of 7'.  If I fix it, and click Next, I move to the "real" Step 7 'Summary' page.

![image](https://cloud.githubusercontent.com/assets/16542988/13006225/47204796-d17f-11e5-8b7e-f944b499b37a.png)

**Comment by ijdickinson** [comment]
Sorry, Carl, I don't follow. Can I have the exact sequence of steps to reproduce this please?

**Comment by carl-t** [comment]
Steps are similar to #15:

Example - I prepare a 'Postcode Area' report, I enter a valid postcode area to use, but at the summary stage (7) I change the Area Type to 'County' (it takes me to Step 2 to do this).  When I click on Next, I am taken to the screen as shown above, i.e. I must enter a valid county but it appears to be at Step 7.

**Comment by ijdickinson** [comment]
Should be fixed now

**Comment by carl-t** [comment]
Numbers are now as expected
