### ISSUE TITLE
Incorrect navigation links on standard-reports application pages

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/standard-reports-ui#21]
Links from the standard-reports app to HPI, PPD and the Qonsole are not correct.

Reported by @der

**Comment by ijdickinson** [comment]
Fixed on beta server

**Comment by MalcolmShazell** [comment]
Ian, link to HPI and PPD work. By Qonsole do you mean the SPARQL Query link?

**Comment by ijdickinson** [comment]
> Ian, link to HPI and PPD work. By Qonsole do you mean the SPARQL Query link?

Yes, sorry. "Qonsole" is our internal product name for the JavaScript SPARQL console component.

**Comment by MalcolmShazell** [comment]
fixed
