### ISSUE TITLE
Back button doesn't work in Chrome if JavaScript is disabled

### ISSUE THREAD

**Issue by carl-t** [epimorphics/standard-reports-ui#22]
All seems to be fine with the Back button until JavaScript is disabled.  Clicking it without JS renders the button with an orange background, but no navigation action is taken:

![image](https://cloud.githubusercontent.com/assets/16542988/13433453/d3d37746-dfc9-11e5-8992-2220f1b1d025.png)

**Comment by carl-t** [comment]
OK, sounds fair to me.  It's not like it crashes or fails, just not the full experience.  Similar discussion on gds.blog.gov.uk:
https://gds.blog.gov.uk/2013/10/21/how-many-people-are-missing-out-on-javascript-enhancement/

**Comment by ijdickinson** [comment]
I've added a change which hides the back link if JavaScript is disabled. So rather than a link that does nothing, non-JS users will experience an absence of a link (which still does nothing!)

**Comment by carl-t** [comment]
Looking good.
