### ISSUE TITLE
usability enhancements

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/standard-reports-ui#25]
POSTCODE DEFINITIONS
Step 2 
Please add postcode level examples 
Postcode area i.e GL
Postcode district i.e GL1
Postcode sector i.e GL1 2

**Comment by ijdickinson** [comment]
Fix deployed to the dev server for confirmation testing.

**Comment by ijdickinson** [comment]
By the way, I corrected "i.e." to "e.g", since we want to provide an example (*exempli gratia*) rather than stating what value should be used (*id est*). Yes, I did take Latin at school, though it was rather a long time time ago :)
