### ISSUE TITLE
Change price banding within reports

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/standard-reports-ui#26]
Alison and I have confirmed we will expand the price banded report categories at the higher end as follows:
The last 2 categories are currently:
1,750,001 - 2,000,000
over 2,000,000

Please amend to:
1,750,001 - 2,000,000 (existing)
2,000,001 - 5,000,000
5,000,001 - 10,000,000
10,000,001 - 20,000,000
Over 20,000,000

**Comment by der** [comment]
Change made and deployed to dev for testing.
