### ISSUE TITLE
User can by-pass auto-complete on area name

### ISSUE THREAD

**Issue by der** [epimorphics/standard-reports-ui#27]
In step 3, when entering a district/county/region name then normally the auto-complete will popup and the user will select that.

However, it is possible for a user to hit <return> before the auto-complete arrives and so submit an entry with an incomplete, incorrect or in-correctly cased name.

One solution would be to normalize and validate the area name in the final step, thus allowing the user to go back and fix the name if necessary.

**Comment by ijdickinson** [comment]
Fix deployed to the dev server for confirmation testing.

**Comment by der** [comment]
Looks good to me, thanks. 

[Assuming as reporter it's appropriate for me to close it. @MalcolmShazell - if that's not right feel free to reopen until QA have verified independently.]
