### ISSUE TITLE
User report gets 'stuck' - doesn't produce results

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/standard-reports-ui#29]
We have had a user query come in regarding a report they are trying to create - attached is the steps to re-create the report and I can confirm it does seem to 'freeze' and not complete - can you take a look please? I suspect something is failing in the background

[Re-create user request.pdf](https://github.com/epimorphics/standard-reports-ui/files/403640/Re-create.user.request.pdf)

**Comment by ijdickinson** [comment]
@der Dave, it looks like this request is getting stuck in the SR-manager queue. I can't quite see what's happening, but I'm not really sure where to look. The query worked OK on the dev server, so I assume it has at least something to do with the production data.

You can see instances of the stuck query on LR-Pres-1-b

**Comment by der** [comment]
I'm looking but can't yet tell in what what it is stuck.

At around 10:00am when that one was kicked off someone asked for standard reports for the whole country for every year possible, plus variants. Since those can take large part of and hour to process each there could be just a VERY long delay. But it does seem to think it has actually been started.

Given the spamming of requests it's a bit hard to sort through. Will keep looking.

**Comment by MalcolmShazell** [comment]
@der yes its very obvious when your report is stuck in a queue behind a big report - this is displaying the 'I've got started it'll take 5 mins screen' AFAIK we haven't experienced reports getting 'stuck' once they've got to this place since go live - they have failed with internal server errors etc FYI I created a report around 12:10 today that stuck - that might help you pin down some details in the logs

**Comment by der** [comment]
@MalcolmShazell You've lost me. What 500 server errors? In what way is 12:10 request stuck? What was the request? Should that be in a separate issue?

**Comment by MalcolmShazell** [comment]
@der I re-created the issue at 12:10 on live i.e. the report outlined in the attached PDF - normally if there was a data error the server would display some sort of internal error - this time the page does not change from the 'the report will take 5 minutes to run' notification, refreshing the page does not change this hence the report appears 'stuck'

**Comment by der** [comment]
@MalcolmShazell OK, that makes sense

**Comment by der** [comment]
I've cleared the stuck entry off the queue, submitted a new request and got a valid looking result back within a couple of minutes, so the report is now in the cache.

Having spent some time looking at this I'm still not sure exactly what went wrong. I can see that the request was submitted as part of a huge batch of standard reports (maybe 50) early this morning.

However, there was a queue entry for it dating back to what looks like the end of May (and another one from a different report dating back to July 21) marked as "in progress". I suspect there was some glitch back in May and attempts to resubmit the identical report were finding that "I'm already working on it" record and not going any further. 

The evidence is not 100% consistent but there certainly was at least that problem.

If we get repeats of this will have to think about better ways to check for and repair queue inconsistencies.
