### ISSUE TITLE
Gemfile.lock contains merge conflicts

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/standard-reports-ui#35]
Bad Gemfile.lock on the staging branch - its got merge conflicts.

CI server reports:

[31mYour Gemfile.lock contains merge conflicts.
       Run `git checkout HEAD -- Gemfile.lock` first to get a clean lock.[0m
       
       ================================================================================
       Error executing action `deploy` on resource 'deploy_revision[/var/www/landregistry/standard-reports]'
       ================================================================================
       
       RuntimeError
       ------------
       Error installing gems or precompiling assets for app standard-reports: exit status = '20'; see output above for more information

**Comment by ijdickinson** [comment]
Should be fixed now

**Comment by bwmcbride** [comment]
CI job running fine now.
