### ISSUE TITLE
December not a selectable month in SR builder

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/standard-reports-ui#37]
The report builder in live is not showing December as a selectable month after publication of decembers file this morning. I does show on pre-prod so I don't think this is a triple store issuee.

![image](https://user-images.githubusercontent.com/6670586/51912789-08896280-23cd-11e9-9735-f54ede4c50ec.png)

**Comment by ijdickinson** [comment]
Initial investigation reveals that the API is not returning the correct value for `latest-month-available`. Why it is doing that, I'm not sure. I will need to ask colleagues for help.

**Comment by MalcolmShazell** [comment]
Ok thanks Ian – given it works in pre-prod is there a code build in PP we could push to live to see if that fixes the problem?

Cheers,
M.

**Comment by ijdickinson** [comment]
@MalcolmShazell We have a diagnosis and a short-term fix. We'll need to discuss a longer term fix as well.

Diagnosis: the API is caching the result of the "latest available month" query for 12 hours. This means that, unless the API webapp is restarted, the wrong value will be returned from the cache for up to 11:59 hours after publication

Short-term fix: we've restarted the API web apps

Longer-term fix: we'll need to consider either the caching strategy, or whether we automatically re-start the API applications after publication

**Comment by ijdickinson** [comment]
After reviewing the code with @der, we've concluded that it would be an appropriate change to reduce the long duration on the cache timeout. The current 12h value is something of a hold-over from a previous (expensive) strategy for calculating the latest available month; the current strategy is based on a cheaper query (or strictly speaking small set of queries). 

@MalcolmShazell We're thinking that dropping the cache time down to one hour would be a reasonable balance between increasing load on the service vs. making it more responsive to data publication. That would mean that the maximum time between data publication and the Standard Reports Generator updating would be 59 mins, and on average it would be ~30 mins. Would that be OK?

If we do the infrastructure changes we proposed in the document I sent a few weeks ago, we can implement a more robust solution then.

**Comment by bwmcbride** [comment]
An alternative would be to restart the apps at the same time as we restart fuseki when installing the new database.

**Comment by bwmcbride** [comment]
The plan is to address this by restarting the tomcat app in the presentation servers when the data is updated, provided this restart can be done fast enough to not significantly effect publication time.

See ops ticket https://epimorphics.codebasehq.com/projects/operations/tickets/334

**Comment by bwmcbride** [comment]
This update is now done.  A test run showed that all new requests were being served based on the new data 55 seconds after the specified publication time.

@MalcolmShazell we believe that should address the presenting issue.
