### ISSUE TITLE
invalid postcodes appearing in sparql query: possible injection attack vulnerability

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/standard-reports-ui#40]
A request from the logs that looks like an attempt at an injection attack:

/app/standard-reports/download-report?utf8=%E2%9C%93&report=avgPrice&areaType=pcDistrict&area=-9646%20UNION%20ALL%20SELECT%2012%2C12%2C12%2C12%2C12%2C12%2C12%2C12%2C12%2C12%23&aggregate=none&period%5B%5D=latest_m&age=any

This results in the report manager app generating a query 

SELECT (COUNT(?transaction) AS ?count) (SUM(?price) AS ?total) ?area ?type WHERE
    {
      ?address  text:query (common:postcode '-9646*' 3000000).
      ?transaction 
        ppi:pricePaid ?price;
        ppi:propertyType ?pt;
        ppi:transactionDate ?date;
        ppi:propertyAddress ?address ;
        ppi:transactionCategory ?category .
         ?address common:postcode ?pc . BIND('-9646 UNION ALL SELECT 12,12,12,12,12,12,12,12,12,12#' AS ?area) FILTER(REPLACE(STR(?pc), '([A-Z0-9]*) .*', '$1') = '-9646 UNION ALL SELECT 12,12,12,12,12,12,12,12,12,12#') FILTER(?date >= '2019-06-01'^^xsd:date && ?date < '2019-07-01'^^xsd:date)
        ?pt rdfs:label ?type .
        FILTER(?pt != common:otherPropertyType && ?category != ppi:additionalPricePaidTransaction) 
    } GROUP BY ?area ?type ORDER BY ?area ?type

so the attacker has succeeded in injecting some crud onto the query.   It may just be possible to inject a functioning query fragment like ?s ?p ?o, though pretty difficult as the attacker can't see the query.

If it is possible, this could be used to mount a denial of service attack.  Such an attack would affect standard reports but not the other services.

Could be addressed in the UI or in ReportManager?

**Comment by bwmcbride** [comment]
This is continuing to happen.  Also seeing keywords like SELECT being injected which raises the suspicion level significantly.

We should up the priority of closing this off.

**Comment by bwmcbride** [comment]
Its slightly tricky to test this because if you put the bad postcode into the UI, the UI rejects it - you have to make the request that actually triggers the report creation.

I have tested with the following command:

 wget "https://lr-ppd-dev-pres.epimorphics.net/app/standard-reports/download-report?utf8=%E2%9C%93&report=avgPrice&areaType=pcArea&area=GU16'eldCVk<'\">DxwXbF*&aggregate=none&period%5B%5D=2018-Q2&age=new"

which is based on a request from the logs that got through this morning.

It is now returning a 400 error.

Assuming the integration tests all still pass - then good to go.

**Comment by ijdickinson** [comment]
Another way to test is to use the UI up to the *Summary* screen, and then edit the URL in the browser. I'm pretty sure this is what people are doing to treat standard reports as a poor-man's (or woman's!) API
