### ISSUE TITLE
Duplicate 'total' rows in report

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/standard-reports-ui#5]
In the following report: http://lr-pres-dev-b.epimorphics.net/app/standard-reports/download-report?utf8=%E2%9C%93&report=banded&areaType=county&area=MERSEYSIDE&aggregate=none&period[]=latest_m&age=any

there are two rows labelled 'total' in both the CSV and Excel downloads

**Comment by der** [comment]
Second total row is for the overall aggregation (which is the same in this case since "aggregate=none") modified backend to suppress the overall total in this case.
