### ISSUE TITLE
Possibly confusing when there are missing steps on the progress indicator when configuring standard report options

### ISSUE THREAD

**Issue by carl-t** [epimorphics/standard-reports-ui#6]
There are a few valid scenarios which do not lead sequentially from step 1 through step 7 when choosing standard report options:

1.	Geographical area "District", specify district, Next, no Step 4 required.
2.	Geographical area "Postcode Sector", specify sector, Next, no Step 4 required.
3.	Geographical area "All England and Wales", Next, no Step 3 required

Consider the possibility of showing a pre-populated page for the missing step, possibly read-only or something similar.

**Comment by ijdickinson** [comment]
See also [the FS-36 ](https://trello.com/c/K56nofC1) Trello card

**Comment by MalcolmShazell** [comment]
works fine
