### ISSUE TITLE
standard reports select a county doesn't have the new LAs

### ISSUE THREAD

**Issue by alexrcoley** [epimorphics/standard-reports-ui#65]
reported by a user (via HMLR)

for example: https://landregistry.data.gov.uk/app/standard-reports/report-design?utf8=%E2%9C%93&report=avgPrice&areaType=county `northamptonshire` was replaced in the data with `north northamptonshire` and `west northamptonshrie` neither are showing in the builder.  The old LA is, but there is no data generated.
[ukhpi-property-type-avg-north-northamptonshire-from-2020-09-01-to-2021-09-01.csv](https://github.com/epimorphics/standard-reports-ui/files/7397016/ukhpi-property-type-avg-north-northamptonshire-from-2020-09-01-to-2021-09-01.csv)

....
From HMLR:

>We have a customer reporting problems with the following report
>All Local Authorities within NORTHAMPTONSHIRE by month from April  2021 to August 2021 – getting 0 results

Average Prices and Volumes of Sales |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
By district for county - NORTHAMPTONSHIRE |   |   |   |   |   |   |   |   |   |  
2021-05 |   |   |   |   |   |   |   |   |   |   |  
Age: any |   |   |   |   |   |   |   |   |   |   |  
Report created on: 2021-10-21

**Comment by alexrcoley** [comment]
yes but the new LAs are not selectable to build a report for

**Comment by ijdickinson** [comment]
Northamptonshire should not be removed from the counties, so that historical data can be accessed. East and North Northamptonshire **are** selectable as aggregation targets under `districts` in step 3 of standard reports:

https://landregistry.data.gov.uk/app/standard-reports/report-design?utf8=%E2%9C%93&report=avgPrice&areaType=district

**Comment by alexrcoley** [comment]
if you type `north northamptionshire` in the search you get `false` as the result
![Google Chrome_2021-10-22 13-27-25@2x](https://user-images.githubusercontent.com/1565598/138453668-2bb63afb-7270-4421-bc7c-849868f61daa.jpg)

**Comment by alexrcoley** [comment]
under districts I can see `east northamptonshire` and `south northamptonshire` but not the `north northamptonshire` or `west northamptonshire`

**Comment by ijdickinson** [comment]
Oops, yes, I see that.

I thought the standard reports application was more data driven, but a quick check shows the county name options are stored in code in `step_select_county.rb`.  So a quick change for @joescottdave to make is to add the new UAs to that list. But in the longer term, there needs to be a ticket to think this through a bit more carefully, and derive the list of counties from the data (but in a performant way).

**Comment by joescottdave** [comment]
South and East Northamptonshire appear in `step_select_district.rb` and not `step_select_county.rb` - inverse for (plain) Northamptonshire.  So the change should be to include North and West with districts and not counties? @ijdickinson @alexrcoley

**Comment by alexrcoley** [comment]
There are now two new unitary councils for Northamptonshire – `North Northamptonshire` and `West Northamptonshire` so I think that means that they should be in the "County, Unitary Authority or Greater London" list and not the "District or London Borough" list.  South and East Northamptonshire were districts.

**Comment by joescottdave** [comment]
Should the `county-features.json` (geometries for the map) be updated to include these too? Do we have this data?

**Comment by alexrcoley** [comment]
@joescottdave if the maps are the same as the ones in the UKHPI app I can point you at the geoJSON
