### ISSUE TITLE
Standard Report Regions

### ISSUE THREAD

**Issue by adeniwale** [epimorphics/standard-reports-ui#8]
The list of regions on the "Select a Region"  Step 3 screen does not tally with the map e.g NORTH on the list and NORTH EAST on the map etc.

List/Map
East Anglia/Eastern
East Midlands/East Midlands
Greater London/London
North/North East
North West/North West
South East/South East
South West/South West
Wales/Wales
West Midlands/West Midlands
Yorks And Humber/Yorks And The Humber

Also CUMBRIA county is coming up in the NORTH region and it seems that it should be in the NORTH WEST region. Same goes for some other regions.

**Comment by der** [comment]
When you say *CUMBRIA county is coming up in the NORTH region* do you mean the visual map boundaries look wrong or that if you select "NORTH" in the list then the resulting report includes entries for CUMBRIA and you don't expect it to?

If that latter then that's worth a separate ticket because that is unrelated to the map labelling.

That said. On the regions spreadsheet supplied by LR then CUBMRIA was in NORTH not in NORTH WEST so that's were we've put it :)

**Comment by adeniwale** [comment]
Yes I meant entry for CUMBRIA is coming up in the report for the NORTH region

**Comment by der** [comment]
OK, so as I say, that's what was specified in the region mapping spreadsheet Sue supplied. What region/county mapping are you using that suggests it should be in NORTH WEST?

**Comment by adeniwale** [comment]
I am just going by the Ordinance Survey map on the screen and I thought I should point it out that this might cause some confusion...

**Comment by adeniwale** [comment]
I am also just noticing that when I click on a region on the map, only the ones with exactly the same name on the list get selected on the list. The others are not selected.

**Comment by ijdickinson** [comment]
> I am also just noticing that when I click on a region on the map, 
> only the ones with exactly the same name on the list get selected 
> on the list. The others are not selected. 

Sorry, Victor, you'll need to say more if we're to understand this. Can you give some specific examples please?

**Comment by der** [comment]
I suspect that what's happening is that the region map might be based on the regions used in HPI which match OS Government Regions. Whereas the regions in the PPD data have slightly different names and different shapes (include different counties).

So if you click on "Eastern" on the map then nothing happens because the region name in the choice list is "East Anglia", whereas if you client "South East" on the map then the "South East" choice on the list is selected because the names match.

**Comment by adeniwale** [comment]
When I click on:

WALES on the map, the button for WALES gets selected on the list
WEST MIDLANDS on the map, the button for WEST MIDLANDS gets selected on the list
NORTH WEST on the map, the button for NORTH WEST gets selected on the list
EAST MIDLANDS on the map, the button for EAST MIDLANDS gets selected on the list
SOUTH EAST on the map, the button for SOUTH EAST gets selected on the list
SOUTH WEST on the map, the button for SOUTH WEST gets selected on the list

EAST ANGLIA, GREATER LONDON, NORTH and YORKS AND HUMBER does not get selected.

**Comment by ijdickinson** [comment]
> I suspect that what's happening is that the region map might be based on the 
> regions used in HPI which match OS Government Regions. 
That's right. I mentioned this at the standup on Monday.

> Whereas the regions in the PPD data have slightly different names 
The names I can correct in the data file (I was aware of East/East Anglia, I hadn't realised until Victor pointed it out that there were more discrepancies)

> and different shapes (include different counties).
Different shapes is a bit more worrying. I'm not sure what to do about that ... unless LR can supply a shape file for their regions (currently I'm using OS data to plot the outlines)

**Comment by ijdickinson** [comment]
> EAST ANGLIA, GREATER LONDON, NORTH and YORKS AND HUMBER does not get selected.

Oh, ok. That's the same as your initial report. I thought that https://github.com/epimorphics/standard-reports-ui/issues/8#issuecomment-173911151 was reporting a new problem. So that's a relief!

**Comment by ijdickinson** [comment]
I have fixed the cases where the map selection and checkbox selection do not meet. As @der says, we should move the Cumbria issue to a separate ticket, where it can be discussed and fixed or closed without change as appropriate.

**Comment by ijdickinson** [comment]
Now that we have a separate ticket for discussing the Cumbria question, I'm going to mark this issue as moving to QA.

**Comment by MalcolmShazell** [comment]
confirm selection of the three regions on the map is now population the correct region on the list
