### ISSUE TITLE
Is Cumbria attached to the correct region?

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/standard-reports-ui#9]
Currently, we have Cumbria in the NORTH region. Geographically, it would more obviously be part of the NORTH-WEST region. We need to check if the current assignment is correct, and if so change the map polygons we use for the NORTH and NORTH WEST regions. See also the discussion under issue #8.

**Comment by MalcolmShazell** [comment]
current assignment is correct for PPD cumbria is in the north, now investigating how we can change the polygons to reflect this.

I'd suggest closing this and raising a new task in trello for sorting out the map polygons

**Comment by MalcolmShazell** [comment]
new task raised so closing this issue
